# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_label.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(495, 388)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(60, 40, 361, 41))
        self.textEdit.setObjectName("textEdit")
        self.RedSlider = QtWidgets.QSlider(Form)
        self.RedSlider.setGeometry(QtCore.QRect(40, 130, 211, 22))
        self.RedSlider.setMaximum(255)
        self.RedSlider.setProperty("value", 255)
        self.RedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RedSlider.setObjectName("RedSlider")
        self.GreenSlider = QtWidgets.QSlider(Form)
        self.GreenSlider.setGeometry(QtCore.QRect(40, 210, 211, 22))
        self.GreenSlider.setMaximum(255)
        self.GreenSlider.setProperty("value", 255)
        self.GreenSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GreenSlider.setObjectName("GreenSlider")
        self.BlueSlider = QtWidgets.QSlider(Form)
        self.BlueSlider.setGeometry(QtCore.QRect(40, 280, 211, 22))
        self.BlueSlider.setMaximum(255)
        self.BlueSlider.setProperty("value", 255)
        self.BlueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.BlueSlider.setObjectName("horizontalSlider_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(210, 320, 75, 51))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(290, 129, 171, 171))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 100, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 180, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 260, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(150, 10, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Red"))
        self.label_2.setText(_translate("Form", "Green"))
        self.label_3.setText(_translate("Form", "Blue"))
        self.label_4.setText(_translate("Form", "Create label"))
