# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 20, 1500, 950))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.widget.setObjectName("widget")
        self.scroll_content_widget = QtWidgets.QWidget(self.widget)
        self.scroll_content_widget.setGeometry(QtCore.QRect(1330, -30, 281, 981))
        self.scroll_content_widget.setObjectName("scroll_content_widget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 1019, 1921, 61))
        self.widget_2.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.widget_2.setObjectName("widget_2")
        self.show_project_name = QtWidgets.QLabel(self.centralwidget)
        self.show_project_name.setGeometry(QtCore.QRect(1640, 10, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.show_project_name.setFont(font)
        self.show_project_name.setAlignment(QtCore.Qt.AlignCenter)
        self.show_project_name.setObjectName("show_project_name")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(1590, 200, 281, 211))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 279, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.NextBut = QtWidgets.QPushButton(self.centralwidget)
        self.NextBut.setGeometry(QtCore.QRect(1770, 900, 121, 61))
        self.NextBut.setObjectName("NextBut")
        self.PreviousBut = QtWidgets.QPushButton(self.centralwidget)
        self.PreviousBut.setGeometry(QtCore.QRect(1580, 900, 121, 61))
        self.PreviousBut.setObjectName("PreviousBut")
        self.ConfirmBut = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmBut.setGeometry(QtCore.QRect(1770, 100, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        self.ConfirmBut.setFont(font)
        self.ConfirmBut.setStyleSheet("QPushButton {\n"
"                background-color: #0CCF06;\n"
"                border: 1px solid black;\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                color: white;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #0FF708;\n"
"            }\n"
"\n"
"")
        self.ConfirmBut.setObjectName("ConfirmBut")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1690, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.go_toBut = QtWidgets.QPushButton(self.centralwidget)
        self.go_toBut.setGeometry(QtCore.QRect(1770, 840, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.go_toBut.setFont(font)
        self.go_toBut.setObjectName("go_toBut")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(1840, 840, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(16)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10000)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.CloseBut = QtWidgets.QPushButton(self.centralwidget)
        self.CloseBut.setGeometry(QtCore.QRect(1610, 100, 91, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(20)
        self.CloseBut.setFont(font)
        self.CloseBut.setStyleSheet("QPushButton {\n"
"                background-color: #CF0000;\n"
"                border: 1px solid black;\n"
"                border-radius: 4px;\n"
"                padding: 5px;\n"
"                color: white;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #ff6666;\n"
"            }\n"
"")
        self.CloseBut.setIconSize(QtCore.QSize(90, 70))
        self.CloseBut.setObjectName("CloseBut")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.show_project_name.setText(_translate("MainWindow", "Project_name"))
        self.NextBut.setText(_translate("MainWindow", "PushButton"))
        self.PreviousBut.setText(_translate("MainWindow", "PushButton"))
        self.ConfirmBut.setText(_translate("MainWindow", "Finish"))
        self.label.setText(_translate("MainWindow", "0/100"))
        self.go_toBut.setText(_translate("MainWindow", "Go to"))
        self.CloseBut.setText(_translate("MainWindow", "Close"))
from . import project_win_rc
